// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Wordmanager.Data.Models;

namespace WordManager.Api.Migrations
{
    [DbContext(typeof(WordManagerContext))]
    partial class WordManagerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.2-rtm-30932");

            modelBuilder.Entity("Wordmanager.Data.Models.Entities.Curriculum", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("FromLanguageId");

                    b.Property<long>("GraduationId");

                    b.Property<long>("IntoLanguageId");

                    b.HasKey("Id");

                    b.HasIndex("FromLanguageId");

                    b.HasIndex("GraduationId");

                    b.HasIndex("IntoLanguageId");

                    b.ToTable("Curricula");
                });

            modelBuilder.Entity("Wordmanager.Data.Models.Entities.Graduation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Level");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("Level")
                        .IsUnique();

                    b.ToTable("Graduations");
                });

            modelBuilder.Entity("Wordmanager.Data.Models.Entities.Language", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CountryCode");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Languages");
                });

            modelBuilder.Entity("Wordmanager.Data.Models.Entities.Translation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("CurriculumId");

                    b.Property<long>("FromWordId");

                    b.Property<long>("IntoWordId");

                    b.Property<byte[]>("Pronounciation");

                    b.HasKey("Id");

                    b.HasIndex("CurriculumId");

                    b.HasIndex("FromWordId")
                        .IsUnique();

                    b.HasIndex("IntoWordId")
                        .IsUnique();

                    b.ToTable("Translations");
                });

            modelBuilder.Entity("Wordmanager.Data.Models.Entities.Word", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("LanguageId");

                    b.Property<string>("Value")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.ToTable("Words");
                });

            modelBuilder.Entity("Wordmanager.Data.Models.Entities.Curriculum", b =>
                {
                    b.HasOne("Wordmanager.Data.Models.Entities.Language", "FromLanguage")
                        .WithMany("FromGraduation")
                        .HasForeignKey("FromLanguageId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Wordmanager.Data.Models.Entities.Graduation", "Graduation")
                        .WithMany("Curricula")
                        .HasForeignKey("GraduationId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Wordmanager.Data.Models.Entities.Language", "IntoLanguage")
                        .WithMany("IntoGraduation")
                        .HasForeignKey("IntoLanguageId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Wordmanager.Data.Models.Entities.Translation", b =>
                {
                    b.HasOne("Wordmanager.Data.Models.Entities.Curriculum", "Curriculum")
                        .WithMany("Translations")
                        .HasForeignKey("CurriculumId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Wordmanager.Data.Models.Entities.Word", "FromWord")
                        .WithOne("FromTranslation")
                        .HasForeignKey("Wordmanager.Data.Models.Entities.Translation", "FromWordId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Wordmanager.Data.Models.Entities.Word", "IntoWord")
                        .WithOne("IntoTranslation")
                        .HasForeignKey("Wordmanager.Data.Models.Entities.Translation", "IntoWordId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Wordmanager.Data.Models.Entities.Word", b =>
                {
                    b.HasOne("Wordmanager.Data.Models.Entities.Language", "Language")
                        .WithMany("Words")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
